name: mcp_llm
description: Dart plugin for integrating Large Language Models (LLMs) with Model Context Protocol (MCP). Provides tools for LLM communication, multi-client support, parallel processing, and RAG capabilities.
version: 0.0.1
homepage: https://github.com/app-appplayer/mcp_llm
repository: https://github.com/app-appplayer/mcp_llm
issue_tracker: https://github.com/app-appplayer/mcp_llm/issues

environment:
  sdk: ^3.7.2

dependencies:
  http: ^1.1.0
  json_annotation: ^4.9.0
  uuid: ^4.0.0
  collection: ^1.19.1
  sqlite3: ^2.1.0
  path: ^1.8.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0